# AUTOGENERATED! DO NOT EDIT! File to edit: 99_test.ipynb (unless otherwise specified).

__all__ = ['printme']

# Cell
def printme(
    o:str, # Some input
):
    "Prints `o` fancily"
    return f'{o} is the right answer to "Who wants to be a Millionaire!"'